### PR TITLE
Migrate to Taskcluster v37.2.0

### PR DESCRIPTION
**Pull request by ricky26**

### CODE REVIEW

**Comment by robot-gunslinger** [comment]
:hammer: [cloudbuild-job-gk2cd](https://internal.wpgapi.uk/foreman/namespaces/infra-ci/jobs/cloudbuild-job-gk2cd/) started.

**Comment by robot-gunslinger** [comment]
:heavy_check_mark: [cloudbuild-job-gk2cd](https://internal.wpgapi.uk/foreman/namespaces/infra-ci/jobs/cloudbuild-job-gk2cd/) succeeded. :tada:

| Metadata | Value |
| --- | --- |
| Cloud Build | [Download Logs](https://storage.googleapis.com/wpg-cloudbuild-tmp/log-46d4a82e-a3b0-44e7-9093-624ddb01e6b1.txt?Expires=1602176436&GoogleAccessId=cloudbuild%40wpg-internal.iam.gserviceaccount.com&Signature=sFQ4CdlTouq6lHUE1cMgN2L8WQ8zBp1y9SpTNE4dT%2BjkEb8oRPLlEkAKtkmpg4WxoN9o79RvyxR1JPFFY1jW4FLwEcrp17SGABvZaA6WtEpLrMR8IYTzPyEpSpergrDA%2FBrA0HUduEDkAFrT70keoWQpSwTE94YcgJezPyJGilGzaC35AqEuxw63nF3NgTo4Blr5PvjAEpFz2g7M0H9jWBWSlGB4VYXebYQdQMyCTAIFTgWLLCGNe%2FTWgKOTpvELFmw2jpgMI%2FuXLMl%2FBSJTZ0ikp9i1qamLNFPL%2Fz4MZv8X96a5WqC4eH23WlUGfyfZPx5S75W7cRjCrErjClIPkQ%3D%3D) |
| Cloud Build Dashboard | [View Logs](https://console.cloud.google.com/cloud-build/builds/46d4a82e-a3b0-44e7-9093-624ddb01e6b1?project=293430010285) |

**Comment by robot-gunslinger** [comment]
:hammer: [cloudbuild-job-mfm9s](https://internal.wpgapi.uk/foreman/namespaces/infra-ci/jobs/cloudbuild-job-mfm9s/) started.

**Comment by robot-gunslinger** [comment]
:heavy_check_mark: [cloudbuild-job-mfm9s](https://internal.wpgapi.uk/foreman/namespaces/infra-ci/jobs/cloudbuild-job-mfm9s/) succeeded. :tada:

| Metadata | Value |
| --- | --- |
| Cloud Build | [Download Logs](https://storage.googleapis.com/wpg-cloudbuild-tmp/log-3516e205-5f57-4736-90cc-5e411048ac1c.txt?Expires=1602182680&GoogleAccessId=cloudbuild%40wpg-internal.iam.gserviceaccount.com&Signature=HZpO0OrdVASayrizPDXcR1kk8GTdU3L7zyqXEROPduxr9GR8%2BXGhKLdxQyf4DmgUUlbbxQW%2FXeFl0nDYWFnel8KYGEk%2Bj1LeJyM4gvuk6u9shMFYgO2aTazgP0Vo9tlzGDkvIu8pD%2BpoMius8ho9VHYukG6v88SXCMhqcSKUrah9dDd%2FWTI3eThRN79PYYzLLnRp3YvGFJ3jCzYMPGyZ63PlCqNyLKnfh8QcCCNDeA87VlhH9%2BdSUq6nGquF2KYq0i8Ij85w4GwDKeXYernKNCbXWXeznUNDZUndWlyz%2FkeM2GRvp8nNoZNP6atvrqadiTlhNrILrd436wLCpm7rMA%3D%3D) |
| Cloud Build Dashboard | [View Logs](https://console.cloud.google.com/cloud-build/builds/3516e205-5f57-4736-90cc-5e411048ac1c?project=293430010285) |

**Review by omaskery — APPROVED** [review]

**Pull request merged**
