### PR TITLE
Update to Taskcluster v37.3.0

### PR DESCRIPTION
**Pull request by ricky26**

### CODE REVIEW

**Comment by robot-gunslinger** [comment]
:hammer: [cloudbuild-job-2hl4v](https://internal.wpgapi.uk/foreman/namespaces/infra-ci/jobs/cloudbuild-job-2hl4v/) started.

**Comment by robot-gunslinger** [comment]
:x: [cloudbuild-job-2hl4v](https://internal.wpgapi.uk/foreman/namespaces/infra-ci/jobs/cloudbuild-job-2hl4v/) failed. 

| Metadata | Value |
| --- | --- |
| Cloud Build | [Download Logs](https://storage.googleapis.com/wpg-cloudbuild-tmp/log-1f77e941-199e-4dee-a054-4b32a862563d.txt?Expires=1603103125&GoogleAccessId=cloudbuild%40wpg-internal.iam.gserviceaccount.com&Signature=hJfzT3fTOLUKc88WKAlTCjQfTFWhhQETU4g%2FUs3Nx5DY56YHfkBajiNqeVH1LTvNnuSPE7rwyfSBNcg%2BSnfeGRARvdirnKgf7OwKyby7aUrd6tE6HDNNMYkPUR4uykz%2Fr%2BcWTM8Paxvvf0XXVsjLYuYL2H77i%2F%2BFn4fADcFd0U7%2B0sb4VdfaBxjK%2FqHeTgdmE0TCZ9nG30E0Vl7HiIn7BPePasFmOc9adxVi7aGjoIYTFE3HVAcQphZiIwOZ%2BfMc2YvxJYwAYfLp2XR0mx2i6oy%2F7tr3QpWzMY2fS%2FD7SZaMoCikiZQIle%2FB2%2F2B%2FqdLrE7UsH9qrRFbhuHZD7ojFQ%3D%3D) |
| Cloud Build Dashboard | [View Logs](https://console.cloud.google.com/cloud-build/builds/1f77e941-199e-4dee-a054-4b32a862563d?project=293430010285) |

**Comment by robot-gunslinger** [comment]
:hammer: [cloudbuild-job-55d8j](https://internal.wpgapi.uk/foreman/namespaces/infra-ci/jobs/cloudbuild-job-55d8j/) started.

**Comment by robot-gunslinger** [comment]
:heavy_check_mark: [cloudbuild-job-55d8j](https://internal.wpgapi.uk/foreman/namespaces/infra-ci/jobs/cloudbuild-job-55d8j/) succeeded. :tada:

| Metadata | Value |
| --- | --- |
| Cloud Build | [Download Logs](https://storage.googleapis.com/wpg-cloudbuild-tmp/log-37e576dd-cd02-442e-a979-af203bd99593.txt?Expires=1603104534&GoogleAccessId=cloudbuild%40wpg-internal.iam.gserviceaccount.com&Signature=bRTCsJGe8tKmZOAxQikxW2S1UTKrv4%2FN7QNP7r7HZ8eKVWeAEOGflBgjqOPUKKtNGlec1JJAwWZgY3MdWbFfeY23HMHSY9JIVRQ8mE0jUkO7c4apQLHLX93buIJu9Ybavxe7S0mCCFAaQBZe1BKk9LfmjztQF54HODke%2BCypbqorXFstn%2FmUn6oJ6nW1TunR%2FrWUgbCOUy9ybu9lcFCIDBiH%2BV%2BgncqbYCgqK%2FqHK4%2FrbZ5giHilnYZp79SvVOTdDVHpmZ5o2T5gKvvq6zuvixd68UOBIg2GG8k8GP5qYKg%2BYAaEwCDnLUj5N5ofilMu7cwLapU4fGJIOTvhWnJ26Q%3D%3D) |
| Cloud Build Dashboard | [View Logs](https://console.cloud.google.com/cloud-build/builds/37e576dd-cd02-442e-a979-af203bd99593?project=293430010285) |

**Review by omaskery — APPROVED** [review]

**Pull request merged**
